# -*- coding: utf-8 -*-

icon = [
"32 32 4 1 ",
"  c #875A7B",
". c #875A7B",
"X c #875A7B",
"o c #FFFFFF",
"oooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooo",
"oooooooooooo.XX..X..oooooooooooo",
"oooooooooo.X....X.X.X.oooooooooo",
"oooooooo.X.X..oo.XX..XX.oooooooo",
"ooooooo.X..oooooo.XooX..Xooooooo",
"oooooo...ooooooooo.ooooX.Xoooooo",
"ooooo.X.oooooooooooXooooX.Xooooo",
"ooooo..oooooooooooo...ooo..ooooo",
"oooo...ooooooo...X.....oo.X.oooo",
"oooo.Xooo..o...oooo.X.X..oXXoooo",
"oooX........oooooooo.Xoo.X...ooo",
"ooo...oo.....oooooooo.oooo.X.ooo",
"oooX.ooX...ooX.oooooo.ooooo..ooo",
"oooX.oX.ooooooX.ooooo.ooooo..ooo",
"oooX...oooooooooXoooo.ooooo..ooo",
"oooX..oooooooooooXooo.ooooo..ooo",
"ooo..XooooooooooooXoo.ooooX..ooo",
"oooX..ooooooooooooo.X.ooooX..ooo",
"oooo..ooooooooooooo...oooo.Xoooo",
"oooo...oooooooooooo...oooXXXoooo",
"oooooX.ooooooooooooX.Xooo..ooooo",
"ooooo.X.oooooooooooX..ooX.Xooooo",
"ooooooX..ooooooooo..oXo..Xoooooo",
"ooooooo.X..ooooooX.ooX..Xooooooo",
"oooooooo.X.X.Xoo.X.X..X.oooooooo",
"oooooooooo.X....X...X.oooooooooo",
"oooooooooooo.XX..X..oooooooooooo",
"oooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooo"
]

