# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(64, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cmbZPL = QtWidgets.QComboBox(self.groupBox)
        self.cmbZPL.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbZPL.setObjectName("cmbZPL")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbZPL)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(64, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmbESCPOS = QtWidgets.QComboBox(self.groupBox)
        self.cmbESCPOS.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbESCPOS.setObjectName("cmbESCPOS")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbESCPOS)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(64, 0))
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spnPort = QtWidgets.QSpinBox(self.groupBox_2)
        self.spnPort.setMinimum(1024)
        self.spnPort.setMaximum(65535)
        self.spnPort.setProperty("value", 8080)
        self.spnPort.setObjectName("spnPort")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spnPort)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"    background-color: #ffffff;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.txtPort = QtWidgets.QLabel(self.groupBox_3)
        self.txtPort.setObjectName("txtPort")
        self.gridLayout.addWidget(self.txtPort, 0, 2, 1, 1)
        self.txtPrinterZPL = QtWidgets.QLabel(self.groupBox_3)
        self.txtPrinterZPL.setStyleSheet("color: red")
        self.txtPrinterZPL.setObjectName("txtPrinterZPL")
        self.gridLayout.addWidget(self.txtPrinterZPL, 1, 2, 1, 1)
        self.txtPrinterESCPOS = QtWidgets.QLabel(self.groupBox_3)
        self.txtPrinterESCPOS.setStyleSheet("color: red")
        self.txtPrinterESCPOS.setObjectName("txtPrinterESCPOS")
        self.gridLayout.addWidget(self.txtPrinterESCPOS, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnTestZPL = QtWidgets.QPushButton(self.groupBox_4)
        self.btnTestZPL.setEnabled(False)
        self.btnTestZPL.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnTestZPL.setObjectName("btnTestZPL")
        self.verticalLayout_2.addWidget(self.btnTestZPL)
        self.btnTestESCPOS = QtWidgets.QPushButton(self.groupBox_4)
        self.btnTestESCPOS.setEnabled(False)
        self.btnTestESCPOS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnTestESCPOS.setObjectName("btnTestESCPOS")
        self.verticalLayout_2.addWidget(self.btnTestESCPOS)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.groupBox_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnReload = QtWidgets.QPushButton(self.frame_2)
        self.btnReload.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnReload.setObjectName("btnReload")
        self.horizontalLayout.addWidget(self.btnReload)
        self.btnApply = QtWidgets.QPushButton(self.frame_2)
        self.btnApply.setEnabled(False)
        self.btnApply.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout.addWidget(self.btnApply)
        self.btnClose = QtWidgets.QPushButton(self.frame_2)
        self.btnClose.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Printer"))
        self.label_2.setText(_translate("Dialog", "ZPL"))
        self.label_3.setText(_translate("Dialog", "ESC/POS"))
        self.groupBox_2.setTitle(_translate("Dialog", "Sevices"))
        self.label.setText(_translate("Dialog", "Port"))
        self.groupBox_3.setTitle(_translate("Dialog", "Status"))
        self.label_4.setText(_translate("Dialog", "Running Port"))
        self.label_5.setText(_translate("Dialog", "ZPL Printer"))
        self.label_6.setText(_translate("Dialog", "ESCPOS Printer"))
        self.txtPort.setText(_translate("Dialog", "N/A"))
        self.txtPrinterZPL.setText(_translate("Dialog", "Disconnected"))
        self.txtPrinterESCPOS.setText(_translate("Dialog", "Disconnected"))
        self.btnTestZPL.setText(_translate("Dialog", "Print Test"))
        self.btnTestESCPOS.setText(_translate("Dialog", "Print Test"))
        self.btnReload.setText(_translate("Dialog", "Reload"))
        self.btnApply.setText(_translate("Dialog", "Apply"))
        self.btnClose.setText(_translate("Dialog", "Close"))
